# This is a basic workflow to help you get started with Actions

name: TestSuite

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  #  schedule:
  #    - cron: '15 * * * *'

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    strategy:
      fail-fast: false
      matrix:
        os:
          - ubuntu-22.04

    runs-on: ${{ matrix.os }}
    env:
        USER: "david-engelmann"
        VIM: "/home/david-engelmann/neovim"
        VIM_INSTALL_PATH: "/home/david-engelmann/.config/nvim"
        VIMRUNTIME: "/usr/share/nvim/runtime"
        SRC_ACCESS_TOKEN: "my-token"
        SRC_ENDPOINT: "http://localhost"
        HOME: "${GITHUB_WORKSPACE}"
    container:
        image: ubuntu:22.04
        options: --user root

    steps:
      #- uses: deploy-sourcegraph-docker/caddy/builtins/http.Caddyfile@main
      - name: Checkout code
        uses: actions/checkout@v3
        #with:
        #    path: nvim_base
        #with:
        #    path: ../../../home/david-engelmann

      - name: Checkout code for Source Graph
        uses: actions/checkout@v3
        with:
            repository: david-engelmann/deploy-sourcegraph-docker
            path: deploy-sourcegraph-docker

      - name: Set Env Vars
        run: |
            echo "HOME=$GITHUB_WORKSPACE" >> $GITHUB_ENV
            echo "CADDYFILE_PATH=/tmp/http.Caddyfile" >> $GITHUB_ENV

      - name: Perm users
        run: useradd -m -s /bin/bash $USER

      - name: Setup Docker
        run: sh docker/scripts/docker_install.sh

      - name: Install Julia
        run: sh docker/scripts/julia_install.sh

      - name: Caddyfile finder
        run: ls -la deploy-sourcegraph-docker

      - name: Caddyfile finder1
        run: ls -la deploy-sourcegraph-docker/caddy

      - name: Caddyfile finder2
        run: ls -la deploy-sourcegraph-docker/caddy/builtins

      - name: Confirm Caddyfile pres
        run: cat deploy-sourcegraph-docker/caddy/builtins/http.Caddyfile

      - name: Chmod
        run: chmod -R +x deploy-sourcegraph-docker

      - name: Caddyfile specificly
        run: chmod +x deploy-sourcegraph-docker/caddy/builtins/http.Caddyfile

      - name: Test http.Caddyfile pres
        run: test -f deploy-sourcegraph-docker/caddy/builtins/http.Caddyfile && echo true || echo false

      - name: Test http.Caddyfile -r
        run: test -r deploy-sourcegraph-docker/caddy/builtins/http.Caddyfile && echo true || echo false

      - name: Test http.Caddyfile -x
        run: test -x deploy-sourcegraph-docker/caddy/builtins/http.Caddyfile && echo true || echo false

      - name: Copy Caddyfile to Known Location
        run: cp deploy-sourcegraph-docker/caddy/builtins/http.Caddyfile /tmp/http.Caddyfile

      - name: Docker Compose up
        run: docker compose -f docker-compose.yml up -d

      - name: Test Dockerfile.caddy -x
        run: pwd && test -x deploy-sourcegraph-docker/caddy/Dockerfile.caddy && echo true || echo false

      - name: Start Sourcegraph
        run: sh docker/scripts/run-docker-compose.sh

      - name: Check running container
        run: docker ps -a

      - name: Mount to container and test install
        run: docker run --pull=never --rm -v ${GITHUB_WORKSPACE}/config:${VIM_INSTALL_PATH} -v ${HOME}:${HOME} --user ${USER} vim-dev-env nvim --headless "+Lazy! sync" +qa

      - name: Run checkhealth
        run: docker run --pull=never --rm -v ${GITHUB_WORKSPACE}/config:${VIM_INSTALL_PATH} -v ${HOME}:${HOME} --user ${USER} vim-dev-env nvim --headless "healthcheck" +qa

      - name: Mount to container and test write to file
        run: docker run --pull=never --rm -v ${GITHUB_WORKSPACE}/config:${VIM_INSTALL_PATH} -v ${HOME}:${HOME} --user ${USER} vim-dev-env nvim --headless -c "1 s/^/hi/" -c "wq" file.txt

      - name: Upload file.text
        uses: actions/upload-artifact@v2
        with:
            name: file.txt
            path: $GITHUB_WORKSPACE/file.txt
