# This is a basic workflow to help you get started with Actions

name: TestSuite

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  #  schedule:
  #    - cron: '15 * * * *'

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    strategy:
      fail-fast: false
      matrix:
        os:
          - ubuntu-22.04

    runs-on: ${{ matrix.os }}
    env:
        USER: "david-engelmann"
        VIM: "/home/david-engelmann/.config/nvim"
        VIMRUNTIME: "/usr/share/nvim/runtime"
    container:
        image: ubuntu:22.04
        options: --user root

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Perm users
        run: useradd -m -s /bin/bash $USER

      - name: Setup Docker
        run: sh docker/scripts/docker_install.sh

      - name: Docker Compose up
        run: docker compose -f docker-compose.yml up -d

      - name: Check running container
        run: docker ps -a

      - name: Mount to container and test install
        run: docker run --pull=never --rm -v ${GITHUB_WORKSPACE}/config:${VIM} -v ${HOME}:${HOME} --user ${USER} vim-dev-env nvim --headless "+Lazy! sync" +qa

      - name: Mount to container and test write to file
        run: docker run --pull=never --rm -v ${GITHUB_WORKSPACE}/config:${VIM} -v ${HOME}:${HOME} --user ${USER} vim-dev-env nvim --headless -c "1 s/^/hi/" -c "wq" file.txt
